// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: consume.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	StartOffset   uint64                 `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	FinOffset     uint64                 `protobuf:"varint,3,opt,name=fin_offset,json=finOffset,proto3" json:"fin_offset,omitempty"`
	StartFlag     *bool                  `protobuf:"varint,4,opt,name=startFlag,proto3,oneof" json:"startFlag,omitempty"`
	EndFlag       *bool                  `protobuf:"varint,5,opt,name=endFlag,proto3,oneof" json:"endFlag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumePayload) Reset() {
	*x = ConsumePayload{}
	mi := &file_consume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumePayload) ProtoMessage() {}

func (x *ConsumePayload) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumePayload.ProtoReflect.Descriptor instead.
func (*ConsumePayload) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumePayload) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ConsumePayload) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ConsumePayload) GetFinOffset() uint64 {
	if x != nil {
		return x.FinOffset
	}
	return 0
}

func (x *ConsumePayload) GetStartFlag() bool {
	if x != nil && x.StartFlag != nil {
		return *x.StartFlag
	}
	return false
}

func (x *ConsumePayload) GetEndFlag() bool {
	if x != nil && x.EndFlag != nil {
		return *x.EndFlag
	}
	return false
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Msg           []byte                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_consume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConsumeResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeResponse) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ConsumeResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ConsumeResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponseList) Reset() {
	*x = ConsumeResponseList{}
	mi := &file_consume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponseList) ProtoMessage() {}

func (x *ConsumeResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponseList.ProtoReflect.Descriptor instead.
func (*ConsumeResponseList) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeResponseList) GetResponses() []*ConsumeResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_consume_proto protoreflect.FileDescriptor

const file_consume_proto_rawDesc = "" +
	"\n" +
	"\rconsume.proto\x12\tdatatypes\"\xcd\x01\n" +
	"\x0eConsumePayload\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x04R\vstartOffset\x12\x1d\n" +
	"\n" +
	"fin_offset\x18\x03 \x01(\x04R\tfinOffset\x12!\n" +
	"\tstartFlag\x18\x04 \x01(\bH\x00R\tstartFlag\x88\x01\x01\x12\x1d\n" +
	"\aendFlag\x18\x05 \x01(\bH\x01R\aendFlag\x88\x01\x01B\f\n" +
	"\n" +
	"_startFlagB\n" +
	"\n" +
	"\b_endFlag\"Y\n" +
	"\x0fConsumeResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\fR\x03msg\"O\n" +
	"\x13ConsumeResponseList\x128\n" +
	"\tresponses\x18\x01 \x03(\v2\x1a.datatypes.ConsumeResponseR\tresponsesB\x1eZ\x1ckafka-clone/server/datatypesb\x06proto3"

var (
	file_consume_proto_rawDescOnce sync.Once
	file_consume_proto_rawDescData []byte
)

func file_consume_proto_rawDescGZIP() []byte {
	file_consume_proto_rawDescOnce.Do(func() {
		file_consume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consume_proto_rawDesc), len(file_consume_proto_rawDesc)))
	})
	return file_consume_proto_rawDescData
}

var file_consume_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_consume_proto_goTypes = []any{
	(*ConsumePayload)(nil),      // 0: datatypes.ConsumePayload
	(*ConsumeResponse)(nil),     // 1: datatypes.ConsumeResponse
	(*ConsumeResponseList)(nil), // 2: datatypes.ConsumeResponseList
}
var file_consume_proto_depIdxs = []int32{
	1, // 0: datatypes.ConsumeResponseList.responses:type_name -> datatypes.ConsumeResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consume_proto_init() }
func file_consume_proto_init() {
	if File_consume_proto != nil {
		return
	}
	file_consume_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consume_proto_rawDesc), len(file_consume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consume_proto_goTypes,
		DependencyIndexes: file_consume_proto_depIdxs,
		MessageInfos:      file_consume_proto_msgTypes,
	}.Build()
	File_consume_proto = out.File
	file_consume_proto_goTypes = nil
	file_consume_proto_depIdxs = nil
}
