// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: produce.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaStatus int32

const (
	KafkaStatus_Accepted KafkaStatus = 0
	KafkaStatus_Error    KafkaStatus = 1
)

// Enum value maps for KafkaStatus.
var (
	KafkaStatus_name = map[int32]string{
		0: "Accepted",
		1: "Error",
	}
	KafkaStatus_value = map[string]int32{
		"Accepted": 0,
		"Error":    1,
	}
)

func (x KafkaStatus) Enum() *KafkaStatus {
	p := new(KafkaStatus)
	*p = x
	return p
}

func (x KafkaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KafkaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_produce_proto_enumTypes[0].Descriptor()
}

func (KafkaStatus) Type() protoreflect.EnumType {
	return &file_produce_proto_enumTypes[0]
}

func (x KafkaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KafkaStatus.Descriptor instead.
func (KafkaStatus) EnumDescriptor() ([]byte, []int) {
	return file_produce_proto_rawDescGZIP(), []int{0}
}

type ProducePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Msg           []byte                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducePayload) Reset() {
	*x = ProducePayload{}
	mi := &file_produce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducePayload) ProtoMessage() {}

func (x *ProducePayload) ProtoReflect() protoreflect.Message {
	mi := &file_produce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducePayload.ProtoReflect.Descriptor instead.
func (*ProducePayload) Descriptor() ([]byte, []int) {
	return file_produce_proto_rawDescGZIP(), []int{0}
}

func (x *ProducePayload) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ProducePayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProducePayload) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KafkaStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=datatypes.KafkaStatus" json:"status,omitempty"`
	StatusMessage *string                `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3,oneof" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_produce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_produce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_produce_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceResponse) GetStatus() KafkaStatus {
	if x != nil {
		return x.Status
	}
	return KafkaStatus_Accepted
}

func (x *ProduceResponse) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

var File_produce_proto protoreflect.FileDescriptor

const file_produce_proto_rawDesc = "" +
	"\n" +
	"\rproduce.proto\x12\tdatatypes\"S\n" +
	"\x0eProducePayload\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\fR\x03msg\"\x80\x01\n" +
	"\x0fProduceResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.datatypes.KafkaStatusR\x06status\x12*\n" +
	"\x0estatus_message\x18\x02 \x01(\tH\x00R\rstatusMessage\x88\x01\x01B\x11\n" +
	"\x0f_status_message*&\n" +
	"\vKafkaStatus\x12\f\n" +
	"\bAccepted\x10\x00\x12\t\n" +
	"\x05Error\x10\x01B\x1eZ\x1ckafka-clone/server/datatypesb\x06proto3"

var (
	file_produce_proto_rawDescOnce sync.Once
	file_produce_proto_rawDescData []byte
)

func file_produce_proto_rawDescGZIP() []byte {
	file_produce_proto_rawDescOnce.Do(func() {
		file_produce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_produce_proto_rawDesc), len(file_produce_proto_rawDesc)))
	})
	return file_produce_proto_rawDescData
}

var file_produce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_produce_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_produce_proto_goTypes = []any{
	(KafkaStatus)(0),        // 0: datatypes.KafkaStatus
	(*ProducePayload)(nil),  // 1: datatypes.ProducePayload
	(*ProduceResponse)(nil), // 2: datatypes.ProduceResponse
}
var file_produce_proto_depIdxs = []int32{
	0, // 0: datatypes.ProduceResponse.status:type_name -> datatypes.KafkaStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_produce_proto_init() }
func file_produce_proto_init() {
	if File_produce_proto != nil {
		return
	}
	file_produce_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_produce_proto_rawDesc), len(file_produce_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_produce_proto_goTypes,
		DependencyIndexes: file_produce_proto_depIdxs,
		EnumInfos:         file_produce_proto_enumTypes,
		MessageInfos:      file_produce_proto_msgTypes,
	}.Build()
	File_produce_proto = out.File
	file_produce_proto_goTypes = nil
	file_produce_proto_depIdxs = nil
}
