// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: datatypes/replication.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                     // Текущая эпоха (терм) Лидера
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`             // ID Лидера
	TopicName     string                 `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`           // Имя топика
	PartitionId   uint32                 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`    // Номер партиции
	TargetOffset  uint64                 `protobuf:"varint,5,opt,name=target_offset,json=targetOffset,proto3" json:"target_offset,omitempty"` // На какой оффсет Слейв должен положить сообщение
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                // Бинарное тело сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_datatypes_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_datatypes_replication_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *AppendEntriesRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AppendEntriesRequest) GetTargetOffset() uint64 {
	if x != nil {
		return x.TargetOffset
	}
	return 0
}

func (x *AppendEntriesRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                  // Эпоха Слейва (для детекта отставания Лидера)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                            // Успешно ли записано на диск Слейва
	MatchOffset   uint64                 `protobuf:"varint,3,opt,name=match_offset,json=matchOffset,proto3" json:"match_offset,omitempty"` // Актуальный оффсет Слейва после записи
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_datatypes_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_datatypes_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetMatchOffset() uint64 {
	if x != nil {
		return x.MatchOffset
	}
	return 0
}

var File_datatypes_replication_proto protoreflect.FileDescriptor

const file_datatypes_replication_proto_rawDesc = "" +
	"\n" +
	"\x1bdatatypes/replication.proto\x12\tdatatypes\"\xc8\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x03 \x01(\tR\ttopicName\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\rR\vpartitionId\x12#\n" +
	"\rtarget_offset\x18\x05 \x01(\x04R\ftargetOffset\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"h\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fmatch_offset\x18\x03 \x01(\x04R\vmatchOffset2h\n" +
	"\x12ReplicationService\x12R\n" +
	"\rAppendEntries\x12\x1f.datatypes.AppendEntriesRequest\x1a .datatypes.AppendEntriesResponseB\fZ\n" +
	"/datatypesb\x06proto3"

var (
	file_datatypes_replication_proto_rawDescOnce sync.Once
	file_datatypes_replication_proto_rawDescData []byte
)

func file_datatypes_replication_proto_rawDescGZIP() []byte {
	file_datatypes_replication_proto_rawDescOnce.Do(func() {
		file_datatypes_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatypes_replication_proto_rawDesc), len(file_datatypes_replication_proto_rawDesc)))
	})
	return file_datatypes_replication_proto_rawDescData
}

var file_datatypes_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datatypes_replication_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),  // 0: datatypes.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 1: datatypes.AppendEntriesResponse
}
var file_datatypes_replication_proto_depIdxs = []int32{
	0, // 0: datatypes.ReplicationService.AppendEntries:input_type -> datatypes.AppendEntriesRequest
	1, // 1: datatypes.ReplicationService.AppendEntries:output_type -> datatypes.AppendEntriesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datatypes_replication_proto_init() }
func file_datatypes_replication_proto_init() {
	if File_datatypes_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatypes_replication_proto_rawDesc), len(file_datatypes_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datatypes_replication_proto_goTypes,
		DependencyIndexes: file_datatypes_replication_proto_depIdxs,
		MessageInfos:      file_datatypes_replication_proto_msgTypes,
	}.Build()
	File_datatypes_replication_proto = out.File
	file_datatypes_replication_proto_goTypes = nil
	file_datatypes_replication_proto_depIdxs = nil
}
