syntax = "proto3";

package datatypes;

option go_package = "/datatypes";

// Сервис, который запускается на каждом брокере для приема реплик
service ReplicationService {
  rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
}

message AppendEntriesRequest {
  uint64 term = 1;          // Текущая эпоха (терм) Лидера
  int32 leader_id = 2;      // ID Лидера
  string topic_name = 3;    // Имя топика
  uint32 partition_id = 4;  // Номер партиции
  uint64 target_offset = 5; // На какой оффсет Слейв должен положить сообщение
  bytes payload = 6;        // Бинарное тело сообщения
}

message AppendEntriesResponse {
  uint64 term = 1;          // Эпоха Слейва (для детекта отставания Лидера)
  bool success = 2;         // Успешно ли записано на диск Слейва
  uint64 match_offset = 3;  // Актуальный оффсет Слейва после записи
}