// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kafka-clone/server/datatypes/topic.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	NumReplicas   int64                  `protobuf:"varint,2,opt,name=numReplicas,proto3" json:"numReplicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPayload) Reset() {
	*x = TopicPayload{}
	mi := &file_kafka_clone_server_datatypes_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPayload) ProtoMessage() {}

func (x *TopicPayload) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_clone_server_datatypes_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPayload.ProtoReflect.Descriptor instead.
func (*TopicPayload) Descriptor() ([]byte, []int) {
	return file_kafka_clone_server_datatypes_topic_proto_rawDescGZIP(), []int{0}
}

func (x *TopicPayload) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TopicPayload) GetNumReplicas() int64 {
	if x != nil {
		return x.NumReplicas
	}
	return 0
}

type TopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResponse) Reset() {
	*x = TopicResponse{}
	mi := &file_kafka_clone_server_datatypes_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResponse) ProtoMessage() {}

func (x *TopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_clone_server_datatypes_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResponse.ProtoReflect.Descriptor instead.
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return file_kafka_clone_server_datatypes_topic_proto_rawDescGZIP(), []int{1}
}

func (x *TopicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_kafka_clone_server_datatypes_topic_proto protoreflect.FileDescriptor

const file_kafka_clone_server_datatypes_topic_proto_rawDesc = "" +
	"\n" +
	"(kafka-clone/server/datatypes/topic.proto\x12\tdatatypes\"O\n" +
	"\fTopicPayload\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12 \n" +
	"\vnumReplicas\x18\x02 \x01(\x03R\vnumReplicas\"'\n" +
	"\rTopicResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06statusB\x1eZ\x1ckafka-clone/server/datatypesb\x06proto3"

var (
	file_kafka_clone_server_datatypes_topic_proto_rawDescOnce sync.Once
	file_kafka_clone_server_datatypes_topic_proto_rawDescData []byte
)

func file_kafka_clone_server_datatypes_topic_proto_rawDescGZIP() []byte {
	file_kafka_clone_server_datatypes_topic_proto_rawDescOnce.Do(func() {
		file_kafka_clone_server_datatypes_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_clone_server_datatypes_topic_proto_rawDesc), len(file_kafka_clone_server_datatypes_topic_proto_rawDesc)))
	})
	return file_kafka_clone_server_datatypes_topic_proto_rawDescData
}

var file_kafka_clone_server_datatypes_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafka_clone_server_datatypes_topic_proto_goTypes = []any{
	(*TopicPayload)(nil),  // 0: datatypes.TopicPayload
	(*TopicResponse)(nil), // 1: datatypes.TopicResponse
}
var file_kafka_clone_server_datatypes_topic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kafka_clone_server_datatypes_topic_proto_init() }
func file_kafka_clone_server_datatypes_topic_proto_init() {
	if File_kafka_clone_server_datatypes_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_clone_server_datatypes_topic_proto_rawDesc), len(file_kafka_clone_server_datatypes_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_clone_server_datatypes_topic_proto_goTypes,
		DependencyIndexes: file_kafka_clone_server_datatypes_topic_proto_depIdxs,
		MessageInfos:      file_kafka_clone_server_datatypes_topic_proto_msgTypes,
	}.Build()
	File_kafka_clone_server_datatypes_topic_proto = out.File
	file_kafka_clone_server_datatypes_topic_proto_goTypes = nil
	file_kafka_clone_server_datatypes_topic_proto_depIdxs = nil
}
