// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: consume.proto

package proto_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumePayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TopicName   string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	PartitionID int64                  `protobuf:"varint,2,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	// Types that are valid to be assigned to StartPosition:
	//
	//	*ConsumePayload_StartOffset
	//	*ConsumePayload_FromBeginning
	StartPosition isConsumePayload_StartPosition `protobuf_oneof:"start_position"`
	// Types that are valid to be assigned to FinPosition:
	//
	//	*ConsumePayload_FinOffset
	//	*ConsumePayload_TillEnd
	FinPosition   isConsumePayload_FinPosition `protobuf_oneof:"fin_position"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumePayload) Reset() {
	*x = ConsumePayload{}
	mi := &file_consume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumePayload) ProtoMessage() {}

func (x *ConsumePayload) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumePayload.ProtoReflect.Descriptor instead.
func (*ConsumePayload) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumePayload) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ConsumePayload) GetPartitionID() int64 {
	if x != nil {
		return x.PartitionID
	}
	return 0
}

func (x *ConsumePayload) GetStartPosition() isConsumePayload_StartPosition {
	if x != nil {
		return x.StartPosition
	}
	return nil
}

func (x *ConsumePayload) GetStartOffset() uint64 {
	if x != nil {
		if x, ok := x.StartPosition.(*ConsumePayload_StartOffset); ok {
			return x.StartOffset
		}
	}
	return 0
}

func (x *ConsumePayload) GetFromBeginning() bool {
	if x != nil {
		if x, ok := x.StartPosition.(*ConsumePayload_FromBeginning); ok {
			return x.FromBeginning
		}
	}
	return false
}

func (x *ConsumePayload) GetFinPosition() isConsumePayload_FinPosition {
	if x != nil {
		return x.FinPosition
	}
	return nil
}

func (x *ConsumePayload) GetFinOffset() uint64 {
	if x != nil {
		if x, ok := x.FinPosition.(*ConsumePayload_FinOffset); ok {
			return x.FinOffset
		}
	}
	return 0
}

func (x *ConsumePayload) GetTillEnd() bool {
	if x != nil {
		if x, ok := x.FinPosition.(*ConsumePayload_TillEnd); ok {
			return x.TillEnd
		}
	}
	return false
}

type isConsumePayload_StartPosition interface {
	isConsumePayload_StartPosition()
}

type ConsumePayload_StartOffset struct {
	StartOffset uint64 `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3,oneof"`
}

type ConsumePayload_FromBeginning struct {
	FromBeginning bool `protobuf:"varint,5,opt,name=from_beginning,json=fromBeginning,proto3,oneof"` // если true, то читаем с начала
}

func (*ConsumePayload_StartOffset) isConsumePayload_StartPosition() {}

func (*ConsumePayload_FromBeginning) isConsumePayload_StartPosition() {}

type isConsumePayload_FinPosition interface {
	isConsumePayload_FinPosition()
}

type ConsumePayload_FinOffset struct {
	FinOffset uint64 `protobuf:"varint,4,opt,name=fin_offset,json=finOffset,proto3,oneof"`
}

type ConsumePayload_TillEnd struct {
	TillEnd bool `protobuf:"varint,6,opt,name=till_end,json=tillEnd,proto3,oneof"` // если true, то читаем до конца и продолжаем стримить
}

func (*ConsumePayload_FinOffset) isConsumePayload_FinPosition() {}

func (*ConsumePayload_TillEnd) isConsumePayload_FinPosition() {}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Msg           []byte                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_consume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConsumeResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeResponse) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ConsumeResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ConsumeResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // например, "нода не in-sync реплика для этой партиции"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponseList) Reset() {
	*x = ConsumeResponseList{}
	mi := &file_consume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponseList) ProtoMessage() {}

func (x *ConsumeResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_consume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponseList.ProtoReflect.Descriptor instead.
func (*ConsumeResponseList) Descriptor() ([]byte, []int) {
	return file_consume_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeResponseList) GetResponses() []*ConsumeResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *ConsumeResponseList) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_consume_proto protoreflect.FileDescriptor

const file_consume_proto_rawDesc = "" +
	"\n" +
	"\rconsume.proto\x12\tdatatypes\"\xff\x01\n" +
	"\x0eConsumePayload\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12 \n" +
	"\vpartitionID\x18\x02 \x01(\x03R\vpartitionID\x12#\n" +
	"\fstart_offset\x18\x03 \x01(\x04H\x00R\vstartOffset\x12'\n" +
	"\x0efrom_beginning\x18\x05 \x01(\bH\x00R\rfromBeginning\x12\x1f\n" +
	"\n" +
	"fin_offset\x18\x04 \x01(\x04H\x01R\tfinOffset\x12\x1b\n" +
	"\btill_end\x18\x06 \x01(\bH\x01R\atillEndB\x10\n" +
	"\x0estart_positionB\x0e\n" +
	"\ffin_position\"Y\n" +
	"\x0fConsumeResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\fR\x03msg\"t\n" +
	"\x13ConsumeResponseList\x128\n" +
	"\tresponses\x18\x01 \x03(\v2\x1a.datatypes.ConsumeResponseR\tresponses\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorB.Z,kafka-clone/server/datatypes/proto-generatedb\x06proto3"

var (
	file_consume_proto_rawDescOnce sync.Once
	file_consume_proto_rawDescData []byte
)

func file_consume_proto_rawDescGZIP() []byte {
	file_consume_proto_rawDescOnce.Do(func() {
		file_consume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consume_proto_rawDesc), len(file_consume_proto_rawDesc)))
	})
	return file_consume_proto_rawDescData
}

var file_consume_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_consume_proto_goTypes = []any{
	(*ConsumePayload)(nil),      // 0: datatypes.ConsumePayload
	(*ConsumeResponse)(nil),     // 1: datatypes.ConsumeResponse
	(*ConsumeResponseList)(nil), // 2: datatypes.ConsumeResponseList
}
var file_consume_proto_depIdxs = []int32{
	1, // 0: datatypes.ConsumeResponseList.responses:type_name -> datatypes.ConsumeResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consume_proto_init() }
func file_consume_proto_init() {
	if File_consume_proto != nil {
		return
	}
	file_consume_proto_msgTypes[0].OneofWrappers = []any{
		(*ConsumePayload_StartOffset)(nil),
		(*ConsumePayload_FromBeginning)(nil),
		(*ConsumePayload_FinOffset)(nil),
		(*ConsumePayload_TillEnd)(nil),
	}
	file_consume_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consume_proto_rawDesc), len(file_consume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consume_proto_goTypes,
		DependencyIndexes: file_consume_proto_depIdxs,
		MessageInfos:      file_consume_proto_msgTypes,
	}.Build()
	File_consume_proto = out.File
	file_consume_proto_goTypes = nil
	file_consume_proto_depIdxs = nil
}
