// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: replication.proto

package proto_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                     // Текущая эпоха (терм) Лидера
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`             // ID Лидера
	TopicName     string                 `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`           // Имя топика
	PartitionId   uint32                 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`    // Номер партиции
	TargetOffset  uint64                 `protobuf:"varint,5,opt,name=target_offset,json=targetOffset,proto3" json:"target_offset,omitempty"` // На какой оффсет Слейв должен положить сообщение
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                // Бинарное тело сообщения
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Оригинальный timestamp записи, назначенный Лидером
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *AppendEntriesRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AppendEntriesRequest) GetTargetOffset() uint64 {
	if x != nil {
		return x.TargetOffset
	}
	return 0
}

func (x *AppendEntriesRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendEntriesRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                  // Эпоха Слейва (для детекта отставания Лидера)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                            // Успешно ли записано на диск Слейва
	MatchOffset   uint64                 `protobuf:"varint,3,opt,name=match_offset,json=matchOffset,proto3" json:"match_offset,omitempty"` // Актуальный оффсет Слейва после записи
	NotInSync     bool                   `protobuf:"varint,4,opt,name=not_in_sync,json=notInSync,proto3" json:"not_in_sync,omitempty"`     // true, если реплика ещё не in-sync (восстанавливает
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetMatchOffset() uint64 {
	if x != nil {
		return x.MatchOffset
	}
	return 0
}

func (x *AppendEntriesResponse) GetNotInSync() bool {
	if x != nil {
		return x.NotInSync
	}
	return false
}

// FetchLogRequest — запрос отстающей реплики к лидеру на выкачивание лога.
type FetchLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`        // Имя топика
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // Номер партиции
	FromOffset    uint64                 `protobuf:"varint,3,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`    // С какого оффсета начинать выкачивание
	MaxMessages   uint32                 `protobuf:"varint,4,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"` // Максимум сообщений в одном ответе (батч)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLogRequest) Reset() {
	*x = FetchLogRequest{}
	mi := &file_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLogRequest) ProtoMessage() {}

func (x *FetchLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLogRequest.ProtoReflect.Descriptor instead.
func (*FetchLogRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{2}
}

func (x *FetchLogRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *FetchLogRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *FetchLogRequest) GetFromOffset() uint64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *FetchLogRequest) GetMaxMessages() uint32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

// LogEntry — одна запись лога (сохраняет оригинальный оффсет и timestamp).
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntry) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// FetchLogResponse — пачка записей лога от лидера.
type FetchLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`                                   // Записи в порядке возрастания оффсета
	HighWatermark uint64                 `protobuf:"varint,2,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"` // Последний доступный оффсет у лидера (nextOffset)
	Leader        bool                   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`                                    // Является ли отвечающая нода лидером партиции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLogResponse) Reset() {
	*x = FetchLogResponse{}
	mi := &file_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLogResponse) ProtoMessage() {}

func (x *FetchLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLogResponse.ProtoReflect.Descriptor instead.
func (*FetchLogResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{4}
}

func (x *FetchLogResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FetchLogResponse) GetHighWatermark() uint64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

func (x *FetchLogResponse) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

var File_replication_proto protoreflect.FileDescriptor

const file_replication_proto_rawDesc = "" +
	"\n" +
	"\x11replication.proto\x12\tdatatypes\"\xe6\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x03 \x01(\tR\ttopicName\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\rR\vpartitionId\x12#\n" +
	"\rtarget_offset\x18\x05 \x01(\x04R\ftargetOffset\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\x88\x01\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fmatch_offset\x18\x03 \x01(\x04R\vmatchOffset\x12\x1e\n" +
	"\vnot_in_sync\x18\x04 \x01(\bR\tnotInSync\"\x97\x01\n" +
	"\x0fFetchLogRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\x12\x1f\n" +
	"\vfrom_offset\x18\x03 \x01(\x04R\n" +
	"fromOffset\x12!\n" +
	"\fmax_messages\x18\x04 \x01(\rR\vmaxMessages\"Z\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x80\x01\n" +
	"\x10FetchLogResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.datatypes.LogEntryR\aentries\x12%\n" +
	"\x0ehigh_watermark\x18\x02 \x01(\x04R\rhighWatermark\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\bR\x06leader2\xad\x01\n" +
	"\x12ReplicationService\x12R\n" +
	"\rAppendEntries\x12\x1f.datatypes.AppendEntriesRequest\x1a .datatypes.AppendEntriesResponse\x12C\n" +
	"\bFetchLog\x12\x1a.datatypes.FetchLogRequest\x1a\x1b.datatypes.FetchLogResponseB.Z,kafka-clone/server/datatypes/proto-generatedb\x06proto3"

var (
	file_replication_proto_rawDescOnce sync.Once
	file_replication_proto_rawDescData []byte
)

func file_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)))
	})
	return file_replication_proto_rawDescData
}

var file_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_replication_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),  // 0: datatypes.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 1: datatypes.AppendEntriesResponse
	(*FetchLogRequest)(nil),       // 2: datatypes.FetchLogRequest
	(*LogEntry)(nil),              // 3: datatypes.LogEntry
	(*FetchLogResponse)(nil),      // 4: datatypes.FetchLogResponse
}
var file_replication_proto_depIdxs = []int32{
	3, // 0: datatypes.FetchLogResponse.entries:type_name -> datatypes.LogEntry
	0, // 1: datatypes.ReplicationService.AppendEntries:input_type -> datatypes.AppendEntriesRequest
	2, // 2: datatypes.ReplicationService.FetchLog:input_type -> datatypes.FetchLogRequest
	1, // 3: datatypes.ReplicationService.AppendEntries:output_type -> datatypes.AppendEntriesResponse
	4, // 4: datatypes.ReplicationService.FetchLog:output_type -> datatypes.FetchLogResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_replication_proto_init() }
func file_replication_proto_init() {
	if File_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_depIdxs,
		MessageInfos:      file_replication_proto_msgTypes,
	}.Build()
	File_replication_proto = out.File
	file_replication_proto_goTypes = nil
	file_replication_proto_depIdxs = nil
}
